apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginpage-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loginpage
  template:
    metadata:
      labels:
        app: loginpage
    spec:
      containers:
      - name: loginpage-container
        image: stewiedocker46/loginpage:latest
        ports:
        - containerPort: 5000
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: "mysql+pymysql://admin:qwertyuiop@my-flask-db.ct8686g6i2km.us-west-2.rds.amazonaws.com/my-flask-db"
